requires "perl", "5.010";
requires "Encode";
requires "HTTP::Headers";
requires "HTTP::Request";
requires "JSON::XS";
requires "LWP::Protocol::https";
requires "LWP::UserAgent";
requires "Moo";
requires "POSIX";
requires "Try::Tiny";
requires "URI";
requires "URI::Escape";
requires "Scalar::Util";

on 'test' => sub {
    requires "HTTP::Request";
    requires "HTTP::Response";
};

on 'develop' => sub {
    requires "Devel::Cover";
};
