FROM michaelpc/perl-base:latest
RUN HOME=/tmp cpanm --notest Dist::Zilla
RUN HOME=/tmp cpanm --notest Encode
RUN HOME=/tmp cpanm --notest File::Slurp
RUN HOME=/tmp cpanm --notest HTTP::Headers
RUN HOME=/tmp cpanm --notest HTTP::Request
RUN HOME=/tmp cpanm --notest INI::ReadPath
RUN HOME=/tmp cpanm --notest JSON::XS
RUN HOME=/tmp cpanm --notest LWP::Protocol::http
RUN HOME=/tmp cpanm --notest LWP::Protocol::https
RUN HOME=/tmp cpanm --notest LWP::UserAgent
RUN HOME=/tmp cpanm --notest Mouse
RUN HOME=/tmp cpanm --notest Net::Curl::Simple
RUN HOME=/tmp cpanm --notest Try::Tiny
RUN HOME=/tmp cpanm --notest URI
RUN HOME=/tmp cpanm --notest Dancer
RUN HOME=/tmp cpanm --notest Test::TCP
RUN HOME=/tmp cpanm --notest Dancer::Plugin::Auth::Basic
